# Generated by Django 5.2.6 on 2026-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='factor',
        ),
        migrations.AddField(
            model_name='category',
            name='co2_per_unit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_code',
            field=models.CharField(default='bolt', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
