# Generated by Django 5.2.6 on 2026-02-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_factor_category_co2_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
