# Generated by Django 5.2.6 on 2026-02-08 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ENG', 'Engineering & Dev'), ('OPS', 'Cloud Operations'), ('SLS', 'Sales & Growth'), ('MKT', 'Marketing'), ('ADM', 'Administration')], default='ENG', max_length=3, verbose_name='Organization Department')),
                ('monthly_budget', models.FloatField(default=500.0, help_text='Target carbon limit in kg CO2e')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
